#Codigo base

In [9]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#Tienda 2

In [11]:
tienda2.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

In [12]:
tienda3.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Secadora de ropa,Electrodomésticos,1285100.0,66600.0,17/12/2021,Camila Rivera,Santa Marta,4,Tarjeta de crédito,4,11.24079,-74.19904
1,Mesa de noche,Muebles,290100.0,13600.0,10/02/2021,Maria Alfonso,Cali,3,Tarjeta de crédito,1,3.43722,-76.52250
2,Guitarra acústica,Instrumentos musicales,303500.0,17400.0,22/01/2023,Lucas Olivera,Bogotá,5,Tarjeta de crédito,3,4.60971,-74.08175
3,Balón de voleibol,Deportes y diversión,58800.0,3300.0,22/03/2022,Pedro Gomez,Barranquilla,4,Tarjeta de crédito,6,10.96854,-74.78132
4,Armario,Muebles,521100.0,25900.0,12/01/2022,Blanca Ramirez,Bogotá,1,Tarjeta de crédito,1,4.60971,-74.08175

In [13]:
tienda4.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Lavavajillas,Electrodomésticos,1084800.0,56000.0,11/11/2022,Rafael Acosta,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175
1,Cama box,Muebles,473800.0,25400.0,03/01/2020,Izabela de León,Cúcuta,5,Tarjeta de crédito,2,7.89391,-72.50782
2,Balón de baloncesto,Deportes y diversión,23700.0,0.0,25/12/2022,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
3,Modelado predictivo,Libros,57700.0,1300.0,23/11/2021,Lucas Olivera,Medellín,3,Nequi,1,6.25184,-75.56359
4,Auriculares,Electrónicos,138900.0,5600.0,25/04/2022,Blanca Ramirez,Bogotá,4,Tarjeta de crédito,7,4.60971,-74.08175

# 🔎 Exploración inicial del dataset

Antes de realizar análisis más detallados, es importante explorar la estructura del conjunto de datos para comprender qué tipo de información contiene.

El dataset incluye datos sobre:

- Productos y categorías
- Precio de venta
- Costos de envío
- Fecha y ubicación de compra
- Evaluaciones de clientes
- Métodos de pago
- Información geográfica de las transacciones

Esta exploración inicial permite identificar las columnas disponibles, los tipos de datos y posibles patrones que serán útiles en los siguientes análisis.

In [14]:
tienda.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

In [15]:
tienda2.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

In [16]:
tienda3.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

In [17]:
tienda4.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

#Estructura del dataset

In [5]:
tienda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [18]:
tienda2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [22]:
tienda3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

In [21]:
tienda4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2358 non-null   object
 1   Categoría del Producto  2358 non-null   object
 2   Precio                  2358 non-null   float64
 3   Costo de envío          2358 non-null   float64
 4   Fecha de Compra         2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Lugar de Compra         2358 non-null   object
 7   Calificación            2358 non-null   int64
 8   Método de pago          2358 non-null   object
 9   Cantidad de cuotas      2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.2+ KB

#Estadísticas básicas

In [6]:
tienda.describe()

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.878679e+05,26018.609580,3.976685,2.943196,5.365283,-74.789417
std,6.146868e+05,32860.001783,1.415370,2.819897,2.287445,1.217827
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.575000e+04,3100.000000,3.000000,1.000000,4.609710,-75.563590
50%,2.353000e+05,12400.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.781000e+05,36000.000000,5.000000,4.000000,6.251840,-74.081750
max,2.977000e+06,160800.000000,5.000000,24.000000,11.544440,-67.923900

In [23]:
tienda2.describe()

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.732274e+05,25216.235693,4.037304,2.902501,5.499753,-74.742963
std,5.955595e+05,31741.375166,1.356153,2.848416,2.351118,1.185997
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.455000e+04,2900.000000,4.000000,1.000000,4.609710,-75.563590
50%,2.182000e+05,11600.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.777000e+05,35450.000000,5.000000,4.000000,6.251840,-74.081750
max,2.953400e+06,162500.000000,5.000000,24.000000,11.544440,-67.923900

In [24]:
tienda3.describe()

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.654598e+05,24805.680373,4.048326,2.967783,5.437076,-74.733463
std,5.806434e+05,30945.889626,1.386426,2.812153,2.405272,1.224572
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.740000e+04,3100.000000,4.000000,1.000000,4.609710,-75.563590
50%,2.263000e+05,11900.000000,5.000000,2.000000,4.609710,-74.199040
75%,6.660500e+05,34950.000000,5.000000,4.000000,6.251840,-74.081750
max,2.968200e+06,158400.000000,5.000000,24.000000,11.544440,-67.923900

In [25]:
tienda4.describe()

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.358000e+03,2358.000000,2358.000000,2358.000000,2358.000000,2358.000000
mean,4.403629e+05,23459.457167,3.995759,2.896098,5.413519,-74.774597
std,5.687556e+05,30279.100836,1.403063,2.730393,2.376728,1.199749
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.340000e+04,2900.000000,3.000000,1.000000,4.609710,-75.563590
50%,2.094500e+05,10950.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.342250e+05,33300.000000,5.000000,4.000000,6.251840,-74.081750
max,2.902200e+06,154700.000000,5.000000,18.000000,11.544440,-67.923900

#1. Análisis de facturación

En este primer análisis se calcula el ingreso total generado por cada tienda.

Para ello se suman los valores de la columna **Precio** de cada conjunto de datos. Esto permite estimar cuánto dinero generó cada tienda a partir de sus ventas.

Este análisis es importante para comparar el desempeño de las tiendas y entender cuál genera mayores ingresos.

In [26]:
facturacion_tienda1 = tienda["Precio"].sum()
facturacion_tienda2 = tienda2["Precio"].sum()
facturacion_tienda3 = tienda3["Precio"].sum()
facturacion_tienda4 = tienda4["Precio"].sum()

print("Facturación Tienda 1:", facturacion_tienda1)
print("Facturación Tienda 2:", facturacion_tienda2)
print("Facturación Tienda 3:", facturacion_tienda3)
print("Facturación Tienda 4:", facturacion_tienda4)

Facturación Tienda 1: 1150880400.0
Facturación Tienda 2: 1116343500.0
Facturación Tienda 3: 1098019600.0
Facturación Tienda 4: 1038375700.0

In [27]:
import pandas as pd

facturacion = pd.DataFrame({
    "Tienda": ["Tienda 1", "Tienda 2", "Tienda 3", "Tienda 4"],
    "Facturación": [
        facturacion_tienda1,
        facturacion_tienda2,
        facturacion_tienda3,
        facturacion_tienda4
    ]
})

facturacion

     Tienda   Facturación
0  Tienda 1  1.150880e+09
1  Tienda 2  1.116344e+09
2  Tienda 3  1.098020e+09
3  Tienda 4  1.038376e+09

# Interpretación

A partir del análisis de facturación se puede observar el ingreso total generado por cada tienda.

Esta información permite identificar qué tienda presenta el mayor volumen de ventas y comparar el desempeño entre ellas.

#2. Ventas por categoría

En este análisis se calcula la cantidad de productos vendidos por categoría en cada tienda.

Para ello se agrupan los datos por la columna **Categoría** y se cuenta el número de ventas de cada tipo de producto. Esto permite identificar cuáles son las categorías más populares en cada tienda.

In [32]:
ventas_categoria_tienda1 = tienda["Categoría del Producto"].value_counts()

ventas_categoria_tienda1

Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [31]:
ventas_categoria_tienda2 = tienda2["Categoría del Producto"].value_counts()

ventas_categoria_tienda2

Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: count, dtype: int64

In [33]:
ventas_categoria_tienda1 = tienda["Categoría del Producto"].value_counts()

ventas_categoria_tienda1

Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [34]:
ventas_categoria_tienda4 = tienda4["Categoría del Producto"].value_counts()

ventas_categoria_tienda4

Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: count, dtype: int64

## Interpretación

A partir del análisis de ventas por categoría se puede observar que la categoría **Muebles** es la más vendida en la tienda, seguida por **Electrónicos**.

Esto indica que los productos relacionados con el hogar y la tecnología presentan una mayor demanda entre los clientes.

Por otro lado, categorías como **Libros** y **Artículos para el hogar** presentan una menor cantidad de ventas en comparación con las demás categorías.

#3. Calificación promedio de la tienda

# Calificación promedio de la tienda

En este análisis se calcula la calificación promedio otorgada por los clientes para cada tienda.

La calificación promedio permite evaluar el nivel de satisfacción de los clientes con los productos y el servicio ofrecido por cada tienda.

In [35]:
calificacion_tienda1 = tienda["Calificación"].mean()

print("Calificación promedio Tienda 1:", calificacion_tienda1)

Calificación promedio Tienda 1: 3.976685036032217

In [36]:
calificacion_tienda2 = tienda2["Calificación"].mean()

print("Calificación promedio Tienda 2:", calificacion_tienda2)

Calificación promedio Tienda 2: 4.037303942348453

In [37]:
calificacion_tienda3 = tienda3["Calificación"].mean()

print("Calificación promedio Tienda 3:", calificacion_tienda3)

Calificación promedio Tienda 3: 4.048325561678677

In [38]:
calificacion_tienda4 = tienda4["Calificación"].mean()

print("Calificación promedio Tienda 4:", calificacion_tienda4)

Calificación promedio Tienda 4: 3.9957591178965224

## Interpretación

La calificación promedio permite evaluar la satisfacción de los clientes con cada tienda.

A partir de este análisis es posible identificar cuál tienda presenta mejores evaluaciones por parte de los clientes y cuál podría necesitar mejoras en la experiencia de compra.

#4. Productos más y menos vendidos

En este análisis se identifican los productos más vendidos y los menos vendidos en cada tienda.

Para ello se cuenta la cantidad de veces que aparece cada producto en el conjunto de datos. Esto permite conocer cuáles son los artículos con mayor demanda y cuáles presentan menor volumen de ventas.

In [39]:
ventas_productos_tienda1 = tienda["Producto"].value_counts()

producto_mas_vendido_tienda1 = ventas_productos_tienda1.idxmax()
producto_menos_vendido_tienda1 = ventas_productos_tienda1.idxmin()

print("Producto más vendido Tienda 1:", producto_mas_vendido_tienda1)
print("Producto menos vendido Tienda 1:", producto_menos_vendido_tienda1)

Producto más vendido Tienda 1: Microondas
Producto menos vendido Tienda 1: Auriculares con micrófono

In [40]:
ventas_productos_tienda2 = tienda2["Producto"].value_counts()

producto_mas_vendido_tienda2 = ventas_productos_tienda2.idxmax()
producto_menos_vendido_tienda2 = ventas_productos_tienda2.idxmin()

print("Producto más vendido Tienda 2:", producto_mas_vendido_tienda2)
print("Producto menos vendido Tienda 2:", producto_menos_vendido_tienda2)

Producto más vendido Tienda 2: Iniciando en programación
Producto menos vendido Tienda 2: Juego de mesa

In [41]:
ventas_productos_tienda3 = tienda3["Producto"].value_counts()

producto_mas_vendido_tienda3 = ventas_productos_tienda3.idxmax()
producto_menos_vendido_tienda3 = ventas_productos_tienda3.idxmin()

print("Producto más vendido Tienda 3:", producto_mas_vendido_tienda3)
print("Producto menos vendido Tienda 3:", producto_menos_vendido_tienda3)

Producto más vendido Tienda 3: Kit de bancas
Producto menos vendido Tienda 3: Bloques de construcción

In [42]:
ventas_productos_tienda4 = tienda4["Producto"].value_counts()

producto_mas_vendido_tienda4 = ventas_productos_tienda4.idxmax()
producto_menos_vendido_tienda4 = ventas_productos_tienda4.idxmin()

print("Producto más vendido Tienda 4:", producto_mas_vendido_tienda4)
print("Producto menos vendido Tienda 4:", producto_menos_vendido_tienda4)

Producto más vendido Tienda 4: Cama box
Producto menos vendido Tienda 4: Guitarra eléctrica

## Interpretación

El análisis de productos más y menos vendidos permite identificar qué artículos tienen mayor aceptación entre los clientes y cuáles presentan menor demanda.

Esta información puede ser útil para ajustar estrategias de inventario, promoción o rotación de productos en cada tienda.

#5. Envío promedio por tienda

En este análisis se calcula el costo de envío promedio para cada tienda.

El objetivo es comprender cuánto se paga, en promedio, por el envío de los productos en cada tienda. Dado que el cliente asume este costo, analizar el valor promedio del envío puede ayudar a identificar posibles diferencias entre tiendas que podrían afectar la decisión de compra.

In [43]:
envio_promedio_tienda1 = tienda["Costo de envío"].mean()

print("Costo de envío promedio Tienda 1:", envio_promedio_tienda1)

Costo de envío promedio Tienda 1: 26018.60958033065

In [44]:
envio_promedio_tienda2 = tienda2["Costo de envío"].mean()

print("Costo de envío promedio Tienda 2:", envio_promedio_tienda2)

Costo de envío promedio Tienda 2: 25216.235693090293

In [45]:
envio_promedio_tienda3 = tienda3["Costo de envío"].mean()

print("Costo de envío promedio Tienda 3:", envio_promedio_tienda3)

Costo de envío promedio Tienda 3: 24805.680373039424

In [46]:
envio_promedio_tienda4 = tienda4["Costo de envío"].mean()

print("Costo de envío promedio Tienda 4:", envio_promedio_tienda4)

Costo de envío promedio Tienda 4: 23459.457167090754